### ISSUE TITLE
Consider switching FluentSyntax::AST to use Cow instead of &str

### ISSUE THREAD

**Issue by zbraniecki** [projectfluent/fluent-rs#104]
AST in `FluentSyntax` currently uses `&str` which means that its basically read-only. As we mature the `fluent-syntax` crate we'll likely want to add a serializer and ability for users to operate on the AST.

There are two ways we could approach it:

1) We could add `OwnedMessage` which would be added to the `Resource::body` like any other node and a way to copy `Message` to a new `OwnedMessage`. This would be quite limiting, but likely sufficient for most use cases.

2) We could switch the AST to use `Cow<&str>` which means it'll still handle `&str` for all basic parsing/runtime work, but allow it to be replaced with owned `String` when modified/added.

(2) sounds tempting, but I'm not sure what are performance/memory consequences.

**Comment by zbraniecki** [comment]
I have a PR now that pushes Cow into AST.

The performance impact is as follows:

parse/"simple": 19.8us -> 22us (+12.2%)
parse/"preferences": 310us -> 329us (+2.2%)
parse/"menubar": 70us -> 76us (+3.3%)

As expected the highest impact is on the simplest AST which would otherwise just use `&str` everywhere.

On the benefit side, having AST as `Cow` allows us to modify AST, and once we add Serializer get the whole `parse->modify->serialize` cycle required for most of the tooling.

Otherwise, we get a faster (lighter?) parser that is "read-only".

Thoughts on that? @manishearth, @stasm?

**Comment by Manishearth** [comment]
> As expected the highest impact is on the simplest AST which would otherwise just use &str everywhere.

The AST isn't directly accessed by most consumers, yes? So it should be fine if it's a bit more complex.

**Comment by zbraniecki** [comment]
Sorry, I misspoke. I meant that the simplest type of Fluent file (you can find our benches fixtures here: https://github.com/projectfluent/fluent-rs/tree/master/fluent-syntax/benches ) is the most affected by adding `Cow`.

I think it's an ok-tradeoff, but my question for you @Manishearth , was more about whether you think that it makes sense for the AST to use Cow to enable modifications of it. I'm not sure what other parser/serializer crates do.

**Comment by zbraniecki** [comment]
I think we have all the data here, what's left is to make the decision.

Is writable AST worth the perf/mem penalty of `Cow`? Is it better to keep the AST/parser read-only and as fast as possible, and maybe introduce a separate AST for serialization with ability to easily convert read-only AST into read/write AST via some `From/Into` conversion?

@stasm, @Manishearth. Thoughts?

**Comment by Pike** [comment]
Are there reasons to expect that `Cow` has impact on the resolver, too? You just generated perf tests for parsing, right?

How would a separate AST look like? Which classes would be affected? I wonder if there's a way to just set the text of a pattern to something known w/out having to convert the whole AST from sliced to string-owning.

**Comment by zbraniecki** [comment]
I also asked on rust discourse, and there are a couple more tricks that may help us - https://users.rust-lang.org/t/fluent-l10n-system-parser-ast-serializer-decision/27507/2

**Comment by Manishearth** [comment]
Most ASTs I've worked with are readonly, and transformations are done via folding over the previous AST (this is basically doing a bunch of moves).

**Comment by zbraniecki** [comment]
I'm pushing it outside of 0.7 milestone. Serializer is not in scope yet, and per Manish comment, users can just fold over previous AST building new nodes as they need them, so this may be just a convenience feature that costs performance on the hot path.

**Comment by Michael-F-Bryan** [comment]
For what it's worth, not having a `Cow<str>` AST isn't a show stopper if you want to create your own tooling... It just makes things a bit more annoying because you've got to thread the needle to make the borrow checker happy.

I created a [`StringPool`](https://gitlab.com/wintech-engineering/fluent-machine-translations/-/blob/eb0454079abfeef6c7e880ae366f281bf37a7d33/src/string_pool.rs) that extends a string reference's lifetime to that of the string pool (it's just a fancy arena). From there you can [traverse the AST](https://gitlab.com/wintech-engineering/fluent-machine-translations/-/blob/eb0454079abfeef6c7e880ae366f281bf37a7d33/src/sub.rs#L14) returning copies of the original nodes or swapping in your own text which is owned by the string pool.

The lifetime annotations get a bit hectic because we're using variance to find a lifetime which satisfies both the `'ast` from our original AST nodes and the `StringPool`. It also doesn't help that the example above has a `&HashMap<&str, String>` which maps some strings from the original AST nodes to a translated version from, for example, Google Translate.

**Comment by kellpossible** [comment]
I've been interacting with the AST a bit lately, and this would have helped/made things easier, especially if there were some clone implementations on the types.That being said, it was possible to work around the lifetime issues.

**Comment by zbraniecki** [comment]
This has now been merged using AST over generic S.
