### ISSUE TITLE
Release 0.1

### ISSUE THREAD

**Issue by zbraniecki** [projectfluent/fluent-rs#8]
Checklist:

  - [x] Patterns without interpolations
  - [x] Message references
  - [x] String-typed external arguments
  - [x] Number-typed external arguments
  - [x] Plural rule for English
  - [x] Select expressions
  - [x] Multi-line patterns
  - [x] Quoted whitespace

**Comment by GlenDC** [comment]
I know this project is still in its very early stages, but I would like to start contributing already and help in releasing this library feature-complete ASAP. This because I believe in (the future of) the L20n project, and also could use this library in some potential future projects of mine.

Because of this, could I simply start implementing features that haven't been checked in this release/milestone issue? And please do tell me in case you are already doing a feature, this way I won't be doing work that's already being done by someone else.

**Comment by stasm** [comment]
@GlenDC Thanks for the interest! We'd love your help with this project.  I remember chatting with @zbraniecki last week: he said he was close to finishing the parser implementation and was waiting for the 0.2 version of the syntax spec to finish.

Only a handful of the planned syntax changes will touch the AST, so I think you could start working on the formatting part even now. The current implementation is extremely limited: it only supports `MessageReferences`.  You can see for yourself: https://github.com/projectfluent/fluent-rs/blob/master/src/context.rs.  Which means that the checklist above is up-to-date.

**Comment by stasm** [comment]
I submitted #17 and #18 which implement the remaining items on the checklist.

**Comment by zbraniecki** [comment]
@stasm are you ok with me releasing fluent-rs 0.1.0 based on the current master?

**Comment by stasm** [comment]
@zbraniecki Can you give me one more day to try to chagge `MessageContext`'s `locales` argument type to a slice?

Also, as part of the release process, I'd like us to file issues for tasks in #9 and create a 0.2 milestone. Some of those tasks might be even 0.3 material.

**Comment by stasm** [comment]
I created milestones 0.1-0.3 at https://github.com/projectfluent/fluent-rs/milestones. Let's use them to scope out the work for the upcoming versions.

**Comment by stasm** [comment]
> Can you give me one more day to try to change MessageContext's locales argument type to a slice?

I filed #22 for this.
